# Action to call a make target in the workspace
name: call-make
description: Call a make target
inputs:
    path:
        description: Path to cd to before calling make
        required: false
    target:
        description: Make target to be called
        required: true
    env:
        description: List (NAME=VALUE,NAME2=VALUE) of env variables to be set
        required: false
runs:
    using: docker
    image: docker://dynod/call-make-action:1.2.0
    args:
        - ${{ inputs.path }}
        - ${{ inputs.target }}
        - ${{ inputs.env }}
