# Action to call a make target in the workspace
name: call-make
description: Call a make target
inputs:
    path:
        description: Path to cd to before calling make
        required: true
    target:
        description: Make target to be called
        required: true
runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.path }}
        - ${{ inputs.target }}
